### ISSUE TITLE
reinforcement.py isn't configured for murasaki

### ISSUE THREAD

**Issue by abizerlokhandwala** [lazydroid/deep-murasaki#3]
While attempting to use reinforcement, it throws an sf2array missing error.
The sf2array function was defined in deep-pink, but I cannot transfer and use those code snippets as the deep pink model is far different from the one used in murasaki, any way to get around this?

**Comment by lazydroid** [comment]
this is a work in the progress, I haven't got to using reinforcements yet. getting a good working model was the higher priority and I'm still looking for the improvements there, since it will give much better results compared to the current model.
